### ISSUE TITLE
onchangestate callback prints in reverse order

### ISSUE THREAD

**Issue by vincent-olivert-riera** [mriehl/fysom#37]
If I want to print the information of every state change I see two simple ways to do it:

1. use a print statement on an `onchangestate` callback function
2. use a print statement on each state callback function

If I **do** use `onchangestate` things are printed in reverse order:

```
$ ./fysom-log-test.py 
next: one -> two
initialize: none -> one
```

If I do **not** use `onchangestate` things are printed in the right order:

```
$ ./fysom-log-test-without-onchangestate.py 
initialize: none -> one
next: one -> two
```

Here is the code example for the version which **does** use `onchangestate`:

```
#!/usr/bin/env python
from fysom import Fysom

class FSM(object):
    def __init__(self, init=True):
        self.fsm = Fysom({
            'initial': 'none',
            'events': [
                {
                    'src': 'none',
                    'name': 'initialize',
                    'dst': 'one'
                },
                {
                    'src': 'one',
                    'name': 'next',
                    'dst': 'two'
                }
            ],
            'callbacks': {
                'onchangestate': self.printstatechange,
                'onone': self.on_one,
                'ontwo': self.on_two
            }
        })
        # Transition to the 'one' state
        self.fsm.initialize()

    @staticmethod
    def printstatechange(event):
        print '{}: {} -> {}'.format(event.event, event.src, event.dst)

    # Callbacks that will be executed for each state
    def on_one(self, _):
            self.fsm.next()

    def on_two(self, _):
            pass


def main():
    FSM()

if __name__ == '__main__':
    main()
```

And here is the one that does **not** use `onchangestate`:

```
#!/usr/bin/env python
from fysom import Fysom

class FSM(object):
    def __init__(self, init=True):
        self.fsm = Fysom({
            'initial': 'none',
            'events': [
                {
                    'src': 'none',
                    'name': 'initialize',
                    'dst': 'one'
                },
                {
                    'src': 'one',
                    'name': 'next',
                    'dst': 'two'
                }
            ],
            'callbacks': {
                'onone': self.on_one,
                'ontwo': self.on_two
            }
        })
        # Transition to the 'one' state
        self.fsm.initialize()

    # Callbacks that will be executed for each state
    def on_one(self, event):
        print '{}: {} -> {}'.format(event.event, event.src, event.dst)
        self.fsm.next()

    def on_two(self, event):
        print '{}: {} -> {}'.format(event.event, event.src, event.dst)


def main():
    FSM()

if __name__ == '__main__':
    main()
```

Why things printed using an `onchangestate` callback are in reverse order?

**Comment by mriehl** [comment]
Hi,

Thanks for the super detailed report. It really helps.

So basically you have a call stack problem. Because you call the next() transition in the one state handler, the fsm is performing a transition "while performing a transition", and the "second", deeper transition completes before the initial transition (because the onone transition blocks until it's done transitioning with next()). Does that make sense?

In other words: onone is actually onenterone. But onenterone is called before onchangestate (you're not really in the new state unless onenter has completed, since you could cancel the transition or do it async).

I think what you want to do here is perform the next() transition in the onafter_initialize. This way the state is changed and onchangestate has been called, which should have the correct order.

Does that help? I guess we should have a section in the callbacks documentation that explains in which callbacks it's safe to call a transition.

**Comment by mriehl** [comment]
Simply moving your code from the `on_state` callback to the `onafter_event` callback (in your example, `onafter_initialize`) should rid you of the problem. Is there a reason why this doesn't work?

Especially if you have a 1:1 state:transition mapping, it shouldn't make a difference if you run in the state callback or the event callback

**Comment by vincent-olivert-riera** [comment]
I see your point, and yes, my simple example works well if I move all callbacks to `onafterevent` callbacks. However this has two important issues for me.

For me it makes more sense to put my code into a state, rather than after an event. I know on which state I am, and I know what it's going to happen there, and depending on what it happens, I trigger one event or another, for transitioning to one state or another.

And also, it prevents me to reuse event names. For instance, my state machine has some states that run one after the other, and the transitions are unconditional, so I just use a `next` transition. One could argue that I could put all the code in just one single state, but that makes (IMHO) the code less readable and the FSM less simple (one thing that I like from FSMs are their simplicity).

So, instead of trying to use `onstatechange` I would use a different solution that works for me.

Thanks a lot for your help.
