### ISSUE TITLE
fysom is getting added to debian packages

### ISSUE THREAD

**Issue by andsens** [mriehl/fysom#8]
Just wanted to bring to your attention that your project is being added as a package to the Debian main repository if all goes well. Thanks for maintaining a nice and simple FSM package!

https://lists.debian.org/debian-cloud/2014/05/msg00038.html

**Comment by stappersg** [comment]
According https://tracker.debian.org/pkg/python-fysom is  the Debian packaging succesfull done.

But why is this issue (from 2014) still open?

**Comment by andsens** [comment]
Nobody thought of closing it :-)
Doing it now.
